config/routes.rb
Calendo::Application.routes.draw do 

  get 'site/index'
  get 'accounts/index'  
  get 'register' => 'registrations#new'
  get 'login' => 'sessions#new'
  get 'logout'=>'sessions#destroy'
  
  constraints(Subdomain) do
    get '/' => 'public#index', as: 'acount_root'
    
    namespace :admin do
       get '/' => 'dashboard#index'
       
       match 'appointments/crud' => 'appointments#crud', as: :appointment_crud, via: [:get, :post]
       get '/customers/search' => 'customers#search', as: 'customer_search'
       
       
       resources :services 
       resources :comments
       resources :appointments
       
       resources :users, :controller => 'customers', :path =>"customers", as: 'customers'
       
       get '/customers/:id/activity' => 'customers#activity', as: 'customer_activity'
       get '/customers/:id/comments' => 'customers#comments', as: 'customer_comments'
       get '/customers/:id/invoicess' => 'customers#invoices', as: 'customer_invoices'
       
       
       resources :users, :controller => 'staff', :path =>"staff", as: 'staff'
       
       get '/schedule' => 'appointments#schedule', as: 'schedule'
              
       get '/account' => 'account#show', as: 'account'
       get '/account/edit' => 'account#edit', as: 'edit_account'
       patch '/account' => 'account#update', as: 'update_account'
       
       get '/profile' => 'profile#show', as: 'profile'
       get '/profile/edit' => 'profile#edit', as: 'edit_profile'
       patch '/profile' => 'profile#update', as: 'update_profile'
       
     
    end
  end
  
  resources :registrations, only: [:index, :create]
  resources :sessions, only: [:create, :destroy]  
  
  root 'site#index'
  

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :account
  has_many :assignments
  has_many :users, through: :assignments
  has_many :schedulables, :dependent => :destroy
  has_many :appointments, through: :schedulables
  
  validates_presence_of :name,:description, :duration, :price
  validates :price, :format => { :with => /\A\d{1,6}(\.\d{0,2})?\z/ , :message => "is invalid. The accepted format is 999999.99 ."}
  
  default_scope { where(account_id: Account.current_id) }
  
  def to_param
    "#{id} #{name}".parameterize
  end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController
  layout "account_admin"
  before_action :authorize!
  before_action :set_service, only: [:show, :edit, :update]
  
  def new
    @service = Service.new
  end
  
  def index
    @services = Service.all
    respond_to do |format|      
        format.html 
        format.json { render json: @services }
    end

    
  end
  
   def create
    @service = Service.new(service_params)   
    
    if @service.save      
      respond_to do |format|
        format.html { redirect_to admin_services_path, notice: 'The service ' + @service.name + ' was successfully created.'  }
        format.json { render action: 'show', status: :created, location: @service }
      end
    else            
      @service.errors.full_messages.each do |msg| 
        logger.info msg
      end
      
      respond_to do |format|        
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end

  end
  
  def update
    
   respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to admin_service_url(:subdomain => current_account.subdomain), notice: 'The service ' + @service.name + ' was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
  end
  
  def show    
    respond_to do |format|      
        format.html 
        format.json { render json: @service }
    end
  end
  
  private

  def set_service
    @service = Service.find(params[:id])
  end
  
  def service_params
      params.require(:service).permit(:name, :description, :duration, :price, :user_ids=>[])
  end
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/views/admin/services/_form.html.erb
<%= form_for [:admin, @service], :html => {:class => "form-horizontal", :role=>"form"} do |f| %>							
	<% if @service.errors.any? %>
		<div id="error_explanation" class="alert alert-danger">
			<h4 style="margin-bottom:0px;"><%= pluralize(@service.errors.count, "error") %> prohibited the service record to be saved!</h4>											      
		</div>
	<% end %>
		<div class="form-group">									
		  	<%= f.label :name, :class=>"col-sm-2 control-label" %>								  	
		  	<div class="col-sm-10">			    
		    	<%= f.text_field :name,  :class=>'form-control', :placeholder=>"New service name" %>
		    	<% if @service.errors[:name].present? %>
					<span class="help-block"><%=:name.to_s.humanize  + ' ' +  @service.errors[:name].join(", ")%></span>
				<% end %> 
		    </div>
		</div>  
		<div class="form-group">
		  	<%= f.label :description, :class=>"col-sm-2 control-label" %>
		  	<div class="col-sm-10">			    
		    	<%= f.text_area :description,  :class=>'form-control', :rows=>"3", :placeholder=>"Description" %>
		    	<% if @service.errors[:description].present? %>
					<span class="help-block"><%=:description.to_s.humanize  + ' ' +  @service.errors[:description].join(", ")%></span>
				<% end %>
		    </div>
		</div> 			
						
		<div class="form-group">
			<label class="col-sm-2 control-label">Status</label>
			<div class="col-sm-10">
				<div class="radio-inline">
					  <label>
						<input type="radio" name="statusRadioGroup" id="optionsRadios1" value="option1" checked>
						Active
					  </label>
					</div>
					<div class="radio-inline">
					  <label>
						<input type="radio" name="statusRadioGroup" id="optionsRadios2" value="option2">
						Inactive (cannot be booked)
					  </label>
					</div>
			</div>
		</div>
		<div class="form-group">
		  	<%= f.label :duration, :class=>"col-sm-2 control-label" %>
		  	<div class="col-sm-3">			    
		    	<%= f.text_field :duration,  :class=>'form-control' %>
		    	<% if @service.errors[:duration].present? %>
					<span class="help-block"><%=:duration.to_s.humanize  + ' ' +  @service.errors[:duration].join(", ")%></span>
				<% end %>
		    </div>
		</div> 
		<div class="form-group">
		  	<%= f.label :price, :class=>"col-sm-2 control-label" %>
		  	<div class="col-sm-3">			    
		    	<%= f.text_field :price,  :class=>'form-control' %>
		    	<% if @service.errors[:price].present? %>
					<span class="help-block"><%=:price.to_s.humanize  + ' ' +  @service.errors[:price].join(", ")%></span>
				<% end %>
		    </div>
		</div>				
		<div class="form-group">
			<label class="col-sm-2 control-label">Booking</label>
			<div class="col-sm-10">
				<div class="radio-inline">
					  <label>
						<input type="radio" name="bookingRadio" id="optionsRadios1" value="option1" checked>
						Online
					  </label>
					</div>
					<div class="radio-inline">
					  <label>
						<input type="radio" name="bookingRadio" id="optionsRadios2" value="option2">
						Staff only
					  </label>
					</div>
			</div>
		</div>		
		<div class="form-group">									
	  	<label class="col-sm-2 control-label">Staff assigned</label>								  	
	  	<div class="col-sm-6">	  		  							    
	    	<%= hidden_field_tag "service[user_ids][]", nil %>
		    <% User.all.with_role(:staff).each do |staff| %>
      			<%= check_box_tag "service[user_ids][]", staff.id, @service.user_ids.include?(staff.id), id: dom_id(staff) %>
      			<%= label_tag dom_id(staff), staff.display_name %><br>
    		<% end %>    	
	    </div>
	</div>				
	<div class="form-group">
		<label class="col-sm-2 control-label"></label>								
	 	<div class="col-md-10" style="margin-top:10px; padding-top:10px;">								
			<%= f.submit :class => 'btn btn-success' %> or <%= link_to 'Cancel', admin_services_path %>	
		</div>
	</div>	
	
<% end %>

app/views/admin/services/create.js.erb
<% if @service.errors.any? %>
	var sAlert = '<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>';
	sAlert = sAlert + '<%=  escape_javascript(flash[:notice]) %>';
	sAlert = sAlert + '<ul>';
	<% @service.errors.full_messages.each do |msg| %>
		sAlert = sAlert + '<li><%= msg %></li>';
	<% end %>
	sAlert = sAlert + '</ul>';
	sAlert = sAlert + '</div>';
	$("#model-error").before(sAlert);
	alert(sAlert);

<% else %>
	$("#alerts").before('<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= escape_javascript(flash[:notice]) %></div>');
	$("#create_service")[0].reset();
	$('#newService').modal('hide');
<% end %>

app/views/admin/services/edit.html.erb
<%- title "Calendo | " + current_account.name + " - Edit service"%>

<section style="padding:15px;">						
	<h3>Edit service: <%= @service.name%> </h3>
	<hr style="margin-top:5px;"/>			
	<%= render 'form' %>	
</section>

<script type="text/javascript">
$( document ).ready(function() {	
	
});
</script>

app/views/admin/services/index.html.erb
<%- title "Calendo | " + current_account.name + " - Services"%>

<section>
	<header class="panel-body">
		<h3 style="margin-top:10px;"><%= current_account.name %> Services 
			<%= link_to new_admin_service_path(@service) do %>
				<span  class="entity-action-link"><i class="fa fa-plus"></i> Create a new service</span> 
			<% end %>
		</h3>						
	<header>
	<table id="service-list" class="table table-hover sorted_table">							  
		  <tbody>
		  	<% @services.each do |service| %>
        		<tr>
				  <td width="35"><i class="fa fa-sort" style="padding-left:10px; cursor:move; "></i></td>								  
				  <td><%= link_to service.name, [:admin, service] %></a></td>
				  <td width="150">Online booking</td>
				  <td width="100"><%= service.duration.to_s %> mins</td>
				  <td width="100"><span style="float:right;"><%= number_to_currency(service.price, precision: 2) %></span> </td>
				</tr>
  			<% end %>								
		  </tbody>
	</table>
</section>


<script type="text/javascript">
$( document ).ready(function() {	
	
});
</script>

app/views/admin/services/new.html.erb
<%- title "Calendo | " + current_account.name + " - New service"%>

<section style="padding:15px;">						
	<h3>Create a new service </h3>
	<hr style="margin-top:5px;"/>			
	
	<%= form_for [:admin, @service], :html => {:class => "form-horizontal", :role=>"form", :id => "create_service"} do |f| %>							
		<% if @service.errors.any? %>
			<div id="error_explanation" class="alert alert-danger">
				<h4 style="margin-bottom:0px;"><%= pluralize(@service.errors.count, "error") %> prohibited the service to be created!</h4>											      
			</div>
		<% end %>
			<div class="form-group">									
			  	<%= f.label :name, :class=>"col-sm-2 control-label" %>								  	
			  	<div class="col-sm-10">			    
			    	<%= f.text_field :name,  :class=>'form-control', :placeholder=>"New service name" %>
			    	<% if @service.errors[:name].present? %>
						<span class="help-block"><%=:name.to_s.humanize  + ' ' +  @service.errors[:name].join(", ")%></span>
					<% end %> 
			    </div>
			</div>  
			<div class="form-group">
			  	<%= f.label :description, :class=>"col-sm-2 control-label" %>
			  	<div class="col-sm-10">			    
			    	<%= f.text_area :description,  :class=>'form-control', :rows=>"3", :placeholder=>"Description" %>
			    	<% if @service.errors[:description].present? %>
						<span class="help-block"><%=:description.to_s.humanize  + ' ' +  @service.errors[:description].join(", ")%></span>
					<% end %>
			    </div>
			</div> 			
							
			<div class="form-group">
				<label class="col-sm-2 control-label">Status</label>
				<div class="col-sm-10">
					<div class="radio-inline">
						  <label>
							<input type="radio" name="statusRadioGroup" id="optionsRadios1" value="option1" checked>
							Active
						  </label>
						</div>
						<div class="radio-inline">
						  <label>
							<input type="radio" name="statusRadioGroup" id="optionsRadios2" value="option2">
							Inactive (cannot be booked)
						  </label>
						</div>
				</div>
			</div>
			<div class="form-group">
			  	<%= f.label :duration, :class=>"col-sm-2 control-label" %>
			  	<div class="col-sm-3">			    
			    	<%= f.text_field :duration,  :class=>'form-control' %>
			    	<% if @service.errors[:duration].present? %>
						<span class="help-block"><%=:duration.to_s.humanize  + ' ' +  @service.errors[:duration].join(", ")%></span>
					<% end %>
			    </div>
			</div> 
			<div class="form-group">
			  	<%= f.label :price, :class=>"col-sm-2 control-label" %>
			  	<div class="col-sm-3">			    
			    	<%= f.text_field :price,  :class=>'form-control' %>
			    	<% if @service.errors[:price].present? %>
						<span class="help-block"><%=:price.to_s.humanize  + ' ' +  @service.errors[:price].join(", ")%></span>
					<% end %>
			    </div>
			</div>				
			<div class="form-group">
				<label class="col-sm-2 control-label">Booking</label>
				<div class="col-sm-10">
					<div class="radio-inline">
						  <label>
							<input type="radio" name="bookingRadio" id="optionsRadios1" value="option1" checked>
							Online
						  </label>
						</div>
						<div class="radio-inline">
						  <label>
							<input type="radio" name="bookingRadio" id="optionsRadios2" value="option2">
							Staff only
						  </label>
						</div>
				</div>
			</div>
			<!--div class="form-group">
				<label class="col-sm-2 control-label">Staff</label>
				<div class="col-sm-10">
					<label class="checkbox-inline">
					  <input type="checkbox" id="inlineCheckbox1" value="option1"> William Bossard
					</label>
					<label class="checkbox-inline">
					  <input type="checkbox" id="inlineCheckbox2" value="option2"> Erica Burcham
					</label>
					<label class="checkbox-inline">
					  <input type="checkbox" id="inlineCheckbox3" value="option3"> Sasha Newsham
					</label>
				</div>
			</div-->				
		<div class="form-group">
			<label class="col-sm-2 control-label"></label>								
		 	<div class="col-md-10" style="margin-top:10px; padding-top:10px;">								
				<%= f.submit 'Create the service', :class => 'btn btn-success' %> or <%= link_to 'Cancel', admin_services_path %>	
			</div>
		</div>								
		
		
	<% end %>
</section>


<script type="text/javascript">
$( document ).ready(function() {	
	
});
</script>

app/views/admin/services/show.html.erb
<%- title "Calendo | " + current_account.name + " - " + @service.name %>

<section class="panel">
	<header class="panel-body">
		<h2 style="margin-top:10px;"><%= @service.name %> 
			<%= link_to edit_admin_service_path(@service) do %>
				<span  class="entity-action-link"><i class="fa fa-edit"></i> Edit this service</span> 
			<% end %> 
			</h2>
		<hr style="margin-top:5px;"/>
		

		<div class="bs-callout bs-callout-info">
			<h4>Basic settings</h4>
			<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
				<div class="col-sm-3" style="text-align:right;" >		
					<label class="normal">Description:</label>
				</div>
				<div class="col-sm-9" >
					<label class="normal"><%= @service.description %></label>
				</div>
			</div>
			<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
				<div class="col-sm-3" style="text-align:right;" >		
					<label class="normal">Category:</label>
				</div>
				<div class="col-sm-9" >
					<label class="normal">Services</label>
				</div>
			</div>
			<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
				<div class="col-sm-3" style="text-align:right;" >		
					<label class="normal">Status:</label>
				</div>
				<div class="col-sm-9" >
					<label class="normal">Active</label>
				</div>
			</div>
			<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
				<div class="col-sm-3" style="text-align:right;" >		
					<label class="normal">Duration:</label>
				</div>
				<div class="col-sm-9" >
					<label class="normal"><%= @service.duration %> mins</label>
				</div>
			</div>
			<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
				<div class="col-sm-3" style="text-align:right;" >		
					<label class="normal">Price:</label>
				</div>
				<div class="col-sm-9" >
					<label class="normal"><%= number_to_currency(@service.price, precision: 2) %></label>
				</div>
			</div>
			<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
				<div class="col-sm-3" style="text-align:right;" >		
					<label class="normal">Booking:</label>
				</div>
				<div class="col-sm-9" >
					<label class="normal">Online</label>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-3" style="text-align:right;" >		
					<label class="normal">Staff assigned:</label>
				</div>
				<div class="col-sm-9" >
					<% @service.users.each do |user|%>
						<label class="normal"><%= link_to user.display_name, edit_admin_staff_path(user) %></label> <br/>						
					<% end %>
					
				</div>
			</div>

		</div>
		
		<div class="bs-callout bs-callout-warning">
			<h4>Advanced settings</h4>
			<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
				<div class="col-sm-3" style="text-align:right;" >		
					<label class="normal">Reminder:</label>
				</div>
				<div class="col-sm-9" >
					<label class="normal">Email reminder is set for 1 day prior the service appointment</label>
				</div>
			</div>
			<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
				<div class="col-sm-3" style="text-align:right;" >		
					<label class="normal">Cancellation:</label>
				</div>
				<div class="col-sm-9" >
					<label class="normal">Clients can cancel up to 1 day prior the service appointment</label>
				</div>
			</div>
			
		</div>
		
		<div class="panel panel-default" style="margin-top:20px;">
			<div class="panel-heading">
				<i class="fa fa-calendar"></i>	Upcoming appointments for this service (next 3)
			</div>
			<div class="panel-body" style="padding: 0px;">
				<table class="table table-striped table-hover">
				  <tbody>
					<tr class="tr-appointment" style="cursor:pointer">
					  <td align="center"><div>Friday, Feb-20-2014</div><div style="color:#666666; font-weight:bold;">09:00 - 10:30</div></td>
					  <td><a href="customer-111.html">Mark Otto </a> (with <span>William Bossard</span>)</td>										  										  
					  <td><span class="label label-success">Confirmed</span></td>
					</tr>
					<tr class="tr-appointment" style="cursor:pointer">
					  <td align="center"><div>Tueday, Mar-22-2014</div><div style="color:#666666; font-weight:bold;">11:00 - 11:30</div></td>
					  <td><a href="#">Jane A. </a> (with Erica Burcham)</td>
					  <td><span class="label label-warning">Not confirmed</span></td>
					</tr>
					<tr class="tr-appointment" style="cursor:pointer">
					  <td align="center"><div>Monday, Mar-27-2014</div><div style="color:#666666; font-weight:bold;">13:00 - 13:30</div></td>
					  <td><a href="#">Rob Donovan </a> (with Sasha Newsham)</td>
					  <td><span class="label label-warning">Not confirmed</span></td>
					</tr>
					
				  </tbody>
				</table>


			</div>
		</div>
		
	<header>
</section>

		