config/routes.rb
Calendo::Application.routes.draw do 

  get 'site/index'
  get 'accounts/index'  
  get 'register' => 'registrations#new'
  get 'login' => 'sessions#new'
  get 'logout'=>'sessions#destroy'
  
  constraints(Subdomain) do
    get '/' => 'public#index', as: 'acount_root'
    
    namespace :admin do
       get '/' => 'dashboard#index'
       
       match 'appointments/crud' => 'appointments#crud', as: :appointment_crud, via: [:get, :post]
       get '/customers/search' => 'customers#search', as: 'customer_search'
       
       
       resources :services 
       resources :comments
       resources :appointments
       
       resources :users, :controller => 'customers', :path =>"customers", as: 'customers'
       
       get '/customers/:id/activity' => 'customers#activity', as: 'customer_activity'
       get '/customers/:id/comments' => 'customers#comments', as: 'customer_comments'
       get '/customers/:id/invoicess' => 'customers#invoices', as: 'customer_invoices'
       
       
       resources :users, :controller => 'staff', :path =>"staff", as: 'staff'
       
       get '/schedule' => 'appointments#schedule', as: 'schedule'
              
       get '/account' => 'account#show', as: 'account'
       get '/account/edit' => 'account#edit', as: 'edit_account'
       patch '/account' => 'account#update', as: 'update_account'
       
       get '/profile' => 'profile#show', as: 'profile'
       get '/profile/edit' => 'profile#edit', as: 'edit_profile'
       patch '/profile' => 'profile#update', as: 'update_profile'
       
     
    end
  end
  
  resources :registrations, only: [:index, :create]
  resources :sessions, only: [:create, :destroy]  
  
  root 'site#index'
  

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  #layout "account", :only => :index
  layout "customer_admin", :except => :index
  before_action :authorize!
  before_action :set_customer_profile, only: [:show, :edit, :update, :activity, :comments, :invoices]
  
  def index
    #@customers = User.all.with_role(:customer) 
    @customers = CustomerProfile.all
    
    
    render(:layout => "layouts/account") 
       
    
    
       
  end
  
  def new
    @customer = User.new
    render(:layout => "layouts/account")
  end
  
  def create
    
    @user = User.new(customer_params) 
    
    @user.generate_password
    logger.info "User password: " + @user.password
    #Required to bypass the "has_secure_password" when an account is created
    @user.password_confirmation = @user.password
    @user.roles = %w[customer]  
    
    if @user.save       
      @customer_profile = CustomerProfile.new(user_id: @user.id)
      if @customer_profile.save             
        respond_to do |format|
          format.html { redirect_to admin_customers_url(:subdomain => current_account.subdomain), notice: 'The customer ' + @user.display_name + ' was successfully added to the account.'  }
          format.json { render action: 'show', status: :created, location: @user }
        end
      else
        respond_to do |format|
          format.html { render action: 'new' }
          format.json { render json: @customer_profile.errors, status: :unprocessable_entity }
        end
      end
      
    else            
      @user.errors.full_messages.each do |msg| 
        logger.debug msg
      end
      
      respond_to do |format|        
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @comment = Comment.new
  end
  
  def activity
    @activities = Activity.where(:recipient_id => @customer.id, :recipient_type => 'CustomerProfile')
    @activities_months = @activities.group_by { |t| t.created_at.beginning_of_month }    
  end
  
  def comments
    
  end
  
  def invoices
    #TODO: add code for invoices when the model is created
  end
  
  
  def search
    @search = params[:query].downcase
    @customers = User.with_role(:customer).includes(:customer_profile).where("lower(display_name) like ?", "%#{@search}%");  
    respond_to do |format|      
      format.json { render :layout => false}      
    end
  end
  
  
private

  def set_customer_profile
    @customer = CustomerProfile.find(params[:id])
  end
  
  def customer_params
      params.require(:user).permit(:email, :display_name, :customer_profile =>{})
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  layout "account"
  before_action :authorize!
  before_action :set_customer, only: [:show, :edit, :update]
  
  def index
    @customers = User.all.with_role(:customer)    
  end
  
  def new
    @customer = User.new
  end
  
  def create
     @customer = User.new(customer_params) 
    flash[:notice] = 'The customer ' + @customer.display_name + ' was successfully added to the account.'  
    redirect_to customers_url(:subdomain => current_account.subdomain)
  end
  
private

  def set_customer
    @customer = User.find(params[:id])
  end
  
  def customer_params
      params.require(:user).permit(:email, :display_name)
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_form.html.erb
								
	<% if @customer.errors.any? %>
		<div id="error_explanation" class="alert alert-danger">
			<h4 style="margin-bottom:0px;"><%= pluralize(@customer.errors.count, "error") %> prohibited the customer record to be saved</h4>
		</div>
	<% end %>
	<div class="form-group">									
	  	<%= f.label :display_name, :class=>"col-sm-2 control-label" %>								  	
	  	<div class="col-sm-6">			    
	    	<%= f.text_field :display_name,  :class=>'form-control', :placeholder=>"Display name" %>
	    	<% if @customer.errors[:display_name].present? %>
				<span class="help-block"><%=:display_name.to_s.humanize  + ' ' +  @customer.errors[:display_name].join(" and ")%></span>
			<% end %> 
	    </div>
	</div>
	
	<div class="form-group">									
	  	<%= f.label :email, :class=>"col-sm-2 control-label" %>								  	
	  	<div class="col-sm-6">	  		  							    
	    	<%= f.text_field :email,  :class=>'form-control', :placeholder=>"Email address" %>
				
	    	<% if @customer.errors[:email].present? %>
				<span class="help-block"><%=:email.to_s.humanize  + ' ' +  @customer.errors[:email].join(" and ")%></span>
			<% end %> 
	    </div>
	</div>
	
	

app/views/admin/customers/activity.html.erb
<section>
	<header class="panel-body">
		<h2 style="margin-top:10px;"><%= @customer.user.display_name %>
		<%= link_to edit_admin_customer_path(@customer) do %>
			<span  class="entity-action-link"><i class="fa fa-edit"></i> Edit this person</span> 
		<% end %>
		</h2>
		<div><span> <i class="fa fa-phone"></i> Phone: 604.111.3345 | <i class="fa fa-envelope-o"></i> Email: <%= @customer.user.email %></span></div>
		<hr style="margin-top:5px;"/>
	</header>
		<div class="timeline">
			<div class="spine"></div>
			
			<% @activities_months.each do |month, activities| %>
				<div class="date_separator">
					<span><%= month.strftime("%B %Y") %></span>
				</div>
				<ul class="columns">			
				<% (activities.sort_by{|k, v| k}.reverse!).each do |activity| %>
					<%= render "admin/activities/#{activity.trackable_type.underscore}/#{activity.action}", activity.trackable_type.underscore.to_sym => activity.trackable %>			
				<% end %>
				</ul>
			<% end %>	
			<div class="date_separator">
					<span>January 2014</span>
				</div>
			<ul class="columns">
				<li>
					<div class="timeline_element blue">
						<div class="timeline_title">
							<span class="timeline_label">Appointment completed</span><span class="timeline_date">11 January 2014</span>
						</div>
						<div class="content">
							<b>Phisyotherapy - 90 minutes</b> on February 3rd, 2014 (11:00-12:00) with William Bossard was completed.
						</div>
						
					</div>
				</li>
				<li>
					<div class="timeline_element orange">
						<div class="timeline_title">
							<span class="timeline_label">Note added</span><span class="timeline_date">10 January 2014</span>
						</div>
						<div class="content">
							<b>Appointment confirmed</b> over the phone with the customer for January 11th
						</div>
						<!--div class="readmore">
							<a class="btn btn-warning" href="#">
								Read More <i class="fa fa-arrow-circle-right"></i>
							</a>
						</div-->
					</div>
				</li>
				<li>
					<div class="timeline_element orange">
						<div class="timeline_title">
							<span class="timeline_label">Note added</span><span class="timeline_date">03 January 2014</span>
						</div>
						<div class="content">
							<b>Appointment scheduled</b> over the phone with the customer for January 11th
						</div>
						<!--div class="readmore">
							<a class="btn btn-warning" href="#">
								Read More <i class="fa fa-arrow-circle-right"></i>
							</a>
						</div-->
					</div>
				</li>
			</ul>

		</div>	
</section>

app/views/admin/customers/comments.html.erb
<section>
	<header class="panel-body">
		<h2 style="margin-top:10px;"><%= @customer.user.display_name %> 
		<%= link_to edit_admin_customer_path(@customer) do %>
				<span  class="entity-action-link"><i class="fa fa-edit"></i> Edit this person</span> 
		<% end %>	
		</h2>
		<div><span> <i class="fa fa-phone"></i> Phone: 604.111.3345 | <i class="fa fa-envelope-o"></i> Email: <%= @customer.user.email %></span></div>
		<hr style="margin-top:5px;"/>
	</header>	
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="fa fa-comments"></i> Comments									
		</div>
		<div class="panel-body" style="padding: 0px;">
			<table class="table table-striped table-hover">
			  <tbody>
			  	<% @customer.comments.each do |comment|%>
			  		<tr class="tr-appointment" style="cursor:pointer">
				  		<td align="center" width="200"><div><%= comment.created_at.strftime("%A, %b-%e-%Y at %l:%M %p")%></div><div style="color:#666666; font-size:12px;"><%= comment.user ? ("Note by " + comment.user.display_name) : "" %></div></td>
				  		<td><%= comment.content%></td>										  										  										  
					</tr>
			  	<% end %>
			  </tbody>
			</table>
		</div>
	</div>		
</section>

app/views/admin/customers/index.html.erb
<%- title "Calendo | " + current_account.name + " - Customers"%>

<section>
	<header class="page_header">
		<h3 style="margin-top:10px;"><%= current_account.name %> customers
			<%= link_to new_admin_customer_path do %>
				<span  class="entity-action-link"><i class="fa fa-plus"></i> Add a new customer</span> 
			<% end %>
		</h3>						
	</header>
	<table id="service-list" class="table table-hover sorted_table">							  
		  <tbody>
		  	<% @customers.each do |customer| %>
        		<tr>				  								  
				  <td><%= link_to customer.user.display_name, admin_customer_path(customer) %></a></td>
				  <td width="200"><%= customer.user.email %></td>				  
				</tr>
  			<% end %>								
		  </tbody>
	</table>
</section>

<script type="text/javascript">
$( document ).ready(function() {	
	
});
</script>

app/views/admin/customers/invoices.html.erb
<section>
	<header class="panel-body">
		<h2 style="margin-top:10px;"><%= @customer.user.display_name %> 
		<%= link_to edit_admin_customer_path(@customer) do %>
				<span  class="entity-action-link"><i class="fa fa-edit"></i> Edit this person</span> 
		<% end %>	
		</h2>
		<div><span> <i class="fa fa-phone"></i> Phone: 604.111.3345 | <i class="fa fa-envelope-o"></i> Email: <%= @customer.user.email %></span></div>
		<hr style="margin-top:5px;"/>
	</header>	
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="fa fa-files-o"></i> Invoices									
		</div>
		<div class="panel-body" style="padding: 0px;">
			<table class="table table-striped table-hover">
			  <tbody>
			  	
			  		<tr class="tr-appointment" style="cursor:pointer">
				  		<td align="center" width="200">
				  			<div>No invoices exist for this customer</div>				  			
				  		</td>				  												  										  										  
					</tr>
			  	
			  </tbody>
			</table>
		</div>
	</div>		
</section>

app/views/admin/customers/new.html.erb
<%- title "Calendo | " + current_account.name + " - New customer"%>


<section>
	<header class="page_header">
		<h3 style="margin-top:10px;"><%= current_account.name %>: Add a new customer</h3>						
	</header>	
	<div class="section-body">
	<%= form_for [:admin, @customer], :url => admin_customers_path(@customer), :html => {:class => "form-horizontal", :role=>"form"} do |f| %>			
		<%= render 'form', :f => f %>	
		<div class="form-group">
			<label class="col-sm-2 control-label"></label>								
		 	<div class="col-md-10" style="margin-top:10px; padding-top:10px;">								
				<%= f.submit "Create customer", :class => 'btn btn-success' %> or <%= link_to 'Cancel', admin_customers_path %>		
			</div>
		</div>		
	<% end %>
	</div>
</section>

app/views/admin/customers/show.html.erb
<section class="panel">
	<header class="panel-body">
		<h2 style="margin-top:10px;"><%= @customer.user.display_name%> 
			<%= link_to edit_admin_customer_path(@customer) do %>
				<span  class="entity-action-link"><i class="fa fa-edit"></i> Edit this person</span> 
			<% end %>
		</h2>
		<div><span> <i class="fa fa-phone"></i> Phone: 604.111.3345 | <i class="fa fa-envelope-o"></i> Email: <%= @customer.user.email%></span></div>
		<hr style="margin-top:5px;"/>
	</header>
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-calendar"></i>	Upcoming appointments									
			</div>
			<div class="panel-body" style="padding: 0px;">
				<table class="table table-striped table-hover">
				  <tbody>
					<tr class="tr-appointment" style="cursor:pointer">
					  <td align="center"><div>Friday, Feb-20-2014</div><div style="color:#666666; font-weight:bold;">09:00 - 10:30</div></td>
					  <td><a href="#">Phisyotherapy - 90 minutes </a> (with <span>William Bossard</span>)</td>										  										  
					  <td><span class="label label-success">Confirmed</span></td>
					</tr>
					<tr class="tr-appointment" style="cursor:pointer">
					  <td align="center"><div>Tueday, Mar-22-2014</div><div style="color:#666666; font-weight:bold;">11:00 - 11:30</div></td>
					  <td><a href="#">Deep Tissue Massage </a> (with Erica Burcham)</td>
					  <td><span class="label label-warning">Not confirmed</span></td>
					</tr>
					<tr class="tr-appointment" style="cursor:pointer">
					  <td align="center"><div>Monday, Mar-27-2014</div><div style="color:#666666; font-weight:bold;">13:00 - 13:30</div></td>
					  <td><a href="#">Hot Stone Massage </a> (with Sasha Newsham)</td>
					  <td><span class="label label-warning">Not confirmed</span></td>
					</tr>
					
				  </tbody>
				</table>


			</div>
		</div>
		
		<section>	
			<%= form_for [:admin, @comment] , :html => {:class => "form-horizontal", :role=>"form", :id => "create_comment"} do |f|%>
				<%= f.hidden_field :customer_profile_id, :value => @customer.id %>			
			  <div class="form-group" style="margin:0 !important;padding-bottom:15px;">
				<label for="customerNote">Add a comment about <%= @customer.user.display_name%>:</label>
				<%= f.text_area :content,  :class=>'form-control', :rows=>"3", :placeholder=>"New note" %>
													
			  </div>
			  <div class="form-group" style="margin:0 !important;">
			  	<%= f.submit "Add this comment", :class => 'btn btn-success pull-right' %> 
			 </div>
			<%end%>
		</section>
	
</section>

<script type="text/javascript">
jQuery.ajaxSetup({ 
  'beforeSend': function(xhr) {xhr.setRequestHeader("Accept", "text/javascript")}
})

$(document).ready(function() {
  	
  	$("#create_comment").submit(function(e) {
  		if ($('#comment_content').val().trim() ==''){
  			console.log('submit code executed');
  			e.preventDefault();
        	return false;
	  	}
	  	else
	  	{
	  		$.post($(this).attr("action"), $(this).serialize(), null, "script");
	 		return false;
	 	}	
  	});
});
	
</script>