config/routes.rb
Calendo::Application.routes.draw do 

  get 'site/index'
  get 'accounts/index'  
  get 'register' => 'registrations#new'
  get 'login' => 'sessions#new'
  get 'logout'=>'sessions#destroy'
  
  constraints(Subdomain) do
    get '/' => 'public#index', as: 'acount_root'
    
    namespace :admin do
       get '/' => 'dashboard#index'
       
       match 'appointments/crud' => 'appointments#crud', as: :appointment_crud, via: [:get, :post]
       get '/customers/search' => 'customers#search', as: 'customer_search'
       
       
       resources :services 
       resources :comments
       resources :appointments
       
       resources :users, :controller => 'customers', :path =>"customers", as: 'customers'
       
       get '/customers/:id/activity' => 'customers#activity', as: 'customer_activity'
       get '/customers/:id/comments' => 'customers#comments', as: 'customer_comments'
       get '/customers/:id/invoicess' => 'customers#invoices', as: 'customer_invoices'
       
       
       resources :users, :controller => 'staff', :path =>"staff", as: 'staff'
       
       get '/schedule' => 'appointments#schedule', as: 'schedule'
              
       get '/account' => 'account#show', as: 'account'
       get '/account/edit' => 'account#edit', as: 'edit_account'
       patch '/account' => 'account#update', as: 'update_account'
       
       get '/profile' => 'profile#show', as: 'profile'
       get '/profile/edit' => 'profile#edit', as: 'edit_profile'
       patch '/profile' => 'profile#update', as: 'update_profile'
       
     
    end
  end
  
  resources :registrations, only: [:index, :create]
  resources :sessions, only: [:create, :destroy]  
  
  root 'site#index'
  

end

app/controllers/admin/profile_controller.rb
class Admin::ProfileController < ApplicationController
  layout "account_admin"
  before_action :authorize!
  before_action :set_profile, only:  [:show, :edit, :update]
  
  def show
    @account = Account.find(current_account.id)
    respond_to do |format|      
        format.html 
        format.json { render json: @account }
    end
  end
  
  
  def edit
    
  end
  
  def update
    if params[:user][:password].blank?
      params[:user].delete :password
      params[:user].delete :password_confirmation
    end


    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_profile_url(:subdomain=>current_account.subdomain), notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end    
  end
  
private 
  
  def set_profile
    @user = current_user
  end
  
  def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :display_name)
  end
  
end

app/helpers/admin/profile_helper.rb
module Admin::ProfileHelper
end

app/views/admin/profile/edit.html.erb
<%- title "Calendo | " + current_account.name + " - Edit profile"%>

<section style="padding:15px;">						
	<h3>Create a new service </h3>
	<hr style="margin-top:5px;"/>			
	<%= form_for [:admin, @user], :url=>admin_profile_path , :html => {:class => "form-horizontal", :role=>"form", :autocomplete=>"off"} do |f| %>							
	<% if @user.errors.any? %>
		<div id="error_explanation" class="alert alert-danger">
			<h4 style="margin-bottom:0px;"><%= pluralize(@user.errors.count, "error") %> prohibited the profile to be updated!</h4>
		</div>
	<% end %>
	<div class="form-group">									
	  	<%= f.label :display_name, :class=>"col-sm-2 control-label" %>								  	
	  	<div class="col-sm-6">			    
	    	<%= f.text_field :display_name,  :class=>'form-control', :placeholder=>"Display name" %>
	    	<% if @user.errors[:display_name].present? %>
				<span class="help-block"><%=:display_name.to_s.humanize  + ' ' +  @user.errors[:display_name].join(" and ")%></span>
			<% end %> 
	    </div>
	</div>
	
	<div class="form-group">									
	  	<%= f.label :email, :class=>"col-sm-2 control-label" %>								  	
	  	<div class="col-sm-6">	  		  							    
	    	<%= f.text_field :email,  :class=>'form-control', :placeholder=>"Email address" %>
				
	    	<% if @user.errors[:email].present? %>
				<span class="help-block"><%=:email.to_s.humanize  + ' ' +  @user.errors[:email].join(" and ")%></span>
			<% end %> 
	    </div>
	</div>
	<div class="form-group">									
	  	<%= f.label :password, :class=>"col-sm-2 control-label" %>								  	
	  	<div class="col-sm-6">	  		  							    
	    	<%= f.password_field :password,  :class=>'form-control', :autocomplete=>"off" %>
				
	    	<% if @user.errors[:password].present? %>
				<span class="help-block"><%=:password.to_s.humanize  + ' ' +  @user.errors[:password].join(" and ")%></span>
			<% end %> 
	    </div>
	</div>
	<div class="form-group">									
	  	<%= f.label :password_confirmation, :class=>"col-sm-2 control-label" %>								  	
	  	<div class="col-sm-6">	  		  							    
	    	<%= f.password_field :password_confirmation,  :class=>'form-control' %>
				
	    	<% if @user.errors[:password_confirmation].present? %>
				<span class="help-block"><%=:password_confirmation.to_s.humanize  + ' ' +  @user.errors[:password_confirmation].join(" and ")%></span>
			<% end %> 
	    </div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label"></label>								
	 	<div class="col-md-10" style="margin-top:10px; padding-top:10px;">								
			<%= f.submit 'Update my profile', :class => 'btn btn-success' %> or <%= link_to 'Cancel', admin_profile_path %>		
		</div>
	</div>		
<% end %>	
</section>

<script type="text/javascript">
$( document ).ready(function() {	
	
});
</script>

app/views/admin/profile/show.html.erb
<%- title "Calendo | " + @account.name + " - " + "My profile" %>

<section style="padding:15px;">
	<header>
		<h3 style="margin-top:10px;">Profile: <%= @user.display_name %> 
		<%= link_to admin_edit_profile_path do %>
				<span  class="entity-action-link"><i class="fa fa-edit"></i> Edit my profile</span> 
			<% end %> 	 
		</h3>
		<hr style="margin-top:5px;"/>
	</header>
	<div class="bs-callout bs-callout-info">
								<h4>Basic settings</h4>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal">Display name:</label>
									</div>
									<div class="col-sm-9" >
										<label class="normal"><%= @user.display_name %></label>
									</div>
								</div>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal">Email:</label>
									</div>
									<div class="col-sm-9" >
										<label class="normal"><%= @user.email %></label>
									</div>
								</div>								
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal">Language:</label>
									</div>
									<div class="col-sm-9" >
										<label class="normal">English US</label>
									</div>
								</div>
								
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal">Description:</label>
									</div>
									<div class="col-sm-9" >
										<label class="normal">Ut nisi dolor, dignissim a aliquet quis, vulputate id dui. Proin ultrices ultrices ligula, dictum varius turpis faucibus non. Curabitur faucibus ultrices nunc, nec aliquet leo tempor cursus</label>
									</div>
								</div>
								
								

							</div>
							
						

</section>