config/routes.rb
Calendo::Application.routes.draw do 

  get 'site/index'
  get 'accounts/index'  
  get 'register' => 'registrations#new'
  get 'login' => 'sessions#new'
  get 'logout'=>'sessions#destroy'
  
  constraints(Subdomain) do
    get '/' => 'public#index', as: 'acount_root'
    
    namespace :admin do
       get '/' => 'dashboard#index'
       
       match 'appointments/crud' => 'appointments#crud', as: :appointment_crud, via: [:get, :post]
       get '/customers/search' => 'customers#search', as: 'customer_search'
       
       
       resources :services 
       resources :comments
       resources :appointments
       
       resources :users, :controller => 'customers', :path =>"customers", as: 'customers'
       
       get '/customers/:id/activity' => 'customers#activity', as: 'customer_activity'
       get '/customers/:id/comments' => 'customers#comments', as: 'customer_comments'
       get '/customers/:id/invoicess' => 'customers#invoices', as: 'customer_invoices'
       
       
       resources :users, :controller => 'staff', :path =>"staff", as: 'staff'
       
       get '/schedule' => 'appointments#schedule', as: 'schedule'
              
       get '/account' => 'account#show', as: 'account'
       get '/account/edit' => 'account#edit', as: 'edit_account'
       patch '/account' => 'account#update', as: 'update_account'
       
       get '/profile' => 'profile#show', as: 'profile'
       get '/profile/edit' => 'profile#edit', as: 'edit_profile'
       patch '/profile' => 'profile#update', as: 'update_profile'
       
     
    end
  end
  
  resources :registrations, only: [:index, :create]
  resources :sessions, only: [:create, :destroy]  
  
  root 'site#index'
  

end

app/models/account.rb
class Account < ActiveRecord::Base
  
  has_many :users
  has_many :customer_profiles
  has_many :services
  has_many :activities
  has_one :owner
  
  has_many :business_hours
  has_many :holidays , :conditions => ["date >= '#{DateTime.now.beginning_of_year.strftime('%Y-%m-%d')}'::date"], :order => "DATE ASC"
  
  accepts_nested_attributes_for :business_hours , allow_destroy: true
  accepts_nested_attributes_for :holidays , allow_destroy: true
  
  validates_presence_of :name
  validates_presence_of :user_email, :user_name, :on => :create  
  validates_format_of :subdomain, :with => /^[A-Za-z0-9-]+$/, :multiline => true, :message => 'The subdomain can only contain alphanumeric characters and dashes.', :allow_blank => true
  validates_exclusion_of :subdomain, :in => %w( support blog www billing help api admin ), :message => "The subdomain <strong>{{value}}</strong> is reserved and unavailable."
  validates_uniqueness_of :subdomain, :case_sensitive => false
  validates_inclusion_of :time_zone, in: ActiveSupport::TimeZone.zones_map(&:name), :if => :time_zone
 
  validate :business_hours_valid

  
 
  before_validation :downcase_subdomain

  RESERVED_SUBDOMAINS = %w(support blog www billing help api admin en fr ro it es de hu).freeze

  def user_name
    @user_name
  end
  def user_name=(val)
    @user_name = val
  end

  def user_email
    @user_email
  end
  def user_email=(val)
    @user_email = val
  end


  def self.current_id=(id)
    Thread.current[:account_id] = id
  end
    
  def self.current_id
    Thread.current[:account_id]
  end
  
  def self.is_reserved_subdomain(subdomain)
    RESERVED_SUBDOMAINS.include? subdomain
  end   

  protected

  def downcase_subdomain
    self.subdomain.downcase! if attribute_present?("subdomain")
  end
  
  private 
  def business_hours_valid
    self.business_hours.each do |bh|
      if Time.parse(bh.open_time)>= Time.parse(bh.close_time)
        errors.add(:business_hours, "open time must be earlier than the close time for: " + bh.day.to_s.humanize)
      end  
    end
    
  end 
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :authorize_access

  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end
  
  def new
    @account=Account.new
  end
  
  def create
    @account = Account.new(post_params)     
    @account.subdomain = @account.name.parameterize
    if @account.save
    
      @user=User.new
      @user.email = @account.user_email   
      @user.account_id= @account.id
      @user.display_name = @account.user_name
      @user.roles = %w[customer staff admin owner]
      @user.generate_password
      logger.info "User password: " + @user.password
      #Required to bypass the "has_secure_password" when an account is created
      @user.password_confirmation = @user.password
    
      if @user.save
        cookies[:_calendo_auth_token] = { :value => @user.auth_token, 
                                            :domain => '.lvh.me' }
        AccountMailer.register_confirmation(@account, @user).deliver
        respond_to do |format|
          format.html { redirect_to admin_url(:subdomain=>@account.subdomain), notice: 'The account ' + @account.name + ' was successfully created.' }
          format.json { render action: 'show', status: :created, location: @account }
        end
      else
        respond_to do |format|
          format.html { render action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
    
  end
 
 # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:account).permit(:name, :user_name, :user_email, :time_zone)
    end
 
 
 def authorize_access
   if current_account
     redirect_to :root  
   end
 end
  
end

app/controllers/admin/account_controller.rb
class Admin::AccountController < ApplicationController
  layout "account_admin"
  before_action :authorize!
  before_action :set_account, only: [:show, :edit, :update]
  
  def edit
    #@account = Account.find(current_account.id)
    
    #TODO: to remove the business hours initialization
    if @account.business_hours.count==0
      BusinessHour::WEEK_DAYS.each do |day|
          @business_hour = BusinessHour.new
          @business_hour.account = @account
          @business_hour.day = day.to_s
          @business_hour.open_time = BusinessHour::DEFAULT_OPEN_TIME
          @business_hour.close_time = BusinessHour::DEFAULT_CLOSE_TIME
          @business_hour.is_closed = false
          @account.business_hours << @business_hour          
      end
      
      @account.save
    end
    
    #@account.holidays.build(:name => "test holiday")
    
    respond_to do |format|      
        format.html 
        format.json { render json: @account }
    end
  end
  
  def show
    @account = Account.find(current_account.id)
    respond_to do |format|      
        format.html 
        format.json { render json: @account }
    end
  end
  
  def update
    
   respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to admin_account_url(:subdomain=>@account.subdomain), notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private 
  
   def set_account
     @account = current_account
    end
  
  def account_params
      params.require(:account).permit(:name, :time_zone, :subdomain, business_hours_attributes: [:id, :day, :open_time, :close_time, :is_closed ], :holidays_attributes => [:id, :name, :date, :_destroy])
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin/account_helper.rb
module Admin::AccountHelper
end

app/views/admin/account/_business_hour_fields.html.erb
<div class="row">
		<%= f.hidden_field :day%>
		<%= f.label f.object.day.humanize, :class=>"col-sm-2 control-label" %>
		<%= f.hidden_field :is_closed, :class=>"is-closed" %>
		
		<% if f.object.is_closed %>
				<div class="col-sm-6" data-view="is-closed" style="display:block; padding-top:9px;">CLOSED</div>
				<div class="col-sm-3"  data-view="is-open" style="display:none; padding-top:5px;">
					<div class="input-group bootstrap-timepicker">
					  <%= f.text_field :open_time,  :class=>'form-control input-small timepicker' %>
					  <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
					</div>
					
					
			  	</div>	 
			  	<div class="col-sm-3"  data-view="is-open" style="display:none; padding-top:5px;">  
			  		<div class="input-group bootstrap-timepicker">
					  <%= f.text_field :close_time,  :class=>'form-control input-small timepicker' %>
					  <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
					</div> 
			  	</div>	
			  	<div class="col-sm-2"  data-view="is-closed">
		  			<button type="button" class="btn btn-link lnk-open">Open this day</button>
			  	</div>
			  	<div class="col-sm-2" style="display:none;"  data-view="is-open">
		  			<button type="button" class="btn btn-link lnk-close">Close this day</button>
			  	</div>
		<% else %>
			<div class="col-sm-6" data-view="is-closed" style="display:none; padding-top:9px;">CLOSED</div>
				<div class="col-sm-3"  data-view="is-open" style="display:block; padding-top:5px;">  
			  		<div class="input-group bootstrap-timepicker">
					  <%= f.text_field :open_time,  :class=>'form-control input-small timepicker' %>
					  <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
					</div>
			  	</div>	 
			  	<div class="col-sm-3"  data-view="is-open" style="display:block; padding-top:5px;">
			  		<div class="input-group bootstrap-timepicker">
					  <%= f.text_field :close_time,  :class=>'form-control input-small timepicker' %>
					  <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
					</div>  
			  		
			  	</div>	
			  	<div class="col-sm-2"  data-view="is-closed" style="display:none;" >
		  			<button type="button" class="btn btn-link lnk-open">Open this day</button>
			  	</div>
			  	<div class="col-sm-2"  data-view="is-open">
		  			<button type="button" class="btn btn-link lnk-close">Close this day</button>
			  	</div>		 
		 <% end %>		 
</div>   

app/views/admin/account/_holiday_fields.html.erb
<div class="form-group row">
	<div class="col-sm-2"></div>	
	<div class="col-sm-5">			    
	    	<%= f.text_field :name,  :class=>'form-control', :placeholder=>"New holiday name" %>
	    </div>
	<div class="col-sm-5" style="width:200px;">
		<div class="input-group input-append date holiday-date" >
			<%= f.text_field :date, :value=>date_to_dd_MMM_yyyy(f.object.date),  :class=>'form-control span2', :readonly=>"readonly"%>
			<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
			<%= f.hidden_field :_destroy %>
		</div>						
	</div>
	<div class="col-sm-2"><button type="button" class="btn btn-link btn-remove-holiday">Remove</button></div>
</div>	

app/views/admin/account/edit.html.erb
<%- title "Calendo | " + current_account.name %>

<section style="padding:15px;">						
	<h3>Editing my account </h3>
	<hr style="margin-top:5px;"/>

<%= form_for [:admin, @account], :html => {:class => "form-horizontal", :role=>"form"} do |f| %>							
	<% if @account.errors.any? %>
		<div id="error_explanation" class="alert alert-danger">
			<h4 style="margin-bottom:0px;"><%= pluralize(@account.errors.count, "error") %> prohibited the account to be updated!</h4>
			<ul>
		      <% @account.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		    </ul>
		</div>
	<% end %>
	<div class="form-group">									
	  	<%= f.label :name, :class=>"col-sm-2 control-label" %>								  	
	  	<div class="col-sm-6">			    
	    	<%= f.text_field :name,  :class=>'form-control', :placeholder=>"New service name" %>
	    	<% if @account.errors[:name].present? %>
				<span class="help-block"><%=:name.to_s.humanize  + ' ' +  @account.errors[:name].join(", ")%></span>
			<% end %> 
	    </div>
	</div>
	
	<div class="form-group">									
	  	<%= f.label :subdomain, :class=>"col-sm-2 control-label" %>								  	
	  	<div class="col-sm-6">
	  		<div class="input-group">
  				<span class="input-group-addon">http://</span>			    
	    		<%= f.text_field :subdomain,  :class=>'form-control', :placeholder=>"subdomain" %>
			 	<span class="input-group-addon">.calendohq.com</span>
			</div>
	    		
	    	<% if @account.errors[:subdomain].present? %>
				<span class="help-block"><%=:subdomain.to_s.humanize  + ' ' +  @account.errors[:subdomain].join(", ")%></span>
			<% end %> 
	    </div>
	</div>

	<div class="form-group">	
	  	<%= f.label :time_zone, :class=>"col-sm-2 control-label" %>	
	  	<div class="col-sm-6">	    
	    	<%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {default: "Pacific Time (US & Canada)"}, {:class=>"form-control"} %>
	    </div>
	</div>
	
	<div>
		<header style="border-bottom:1px solid #DDDDDD; margin-top:15px; margin-bottom:10px;"><h4>Business hours</h4>
		</header>	
		<%= f.fields_for :business_hours, f.object.business_hours.order(:id) do |builder| %>
			<%= render 'business_hour_fields', f: builder %>
   		<% end %>
	</div>
	
	<div>
		<header style="border-bottom:1px solid #DDDDDD; margin-top:15px; margin-bottom:10px;"><h4>Holidays</h4>
		</header>	
		<%= f.fields_for :holidays do |builder| %>
			<%= render 'holiday_fields', f: builder %>
   		<% end %>
   		<%= link_to_add_fields "Add a new holiday", f, :holidays %>
	</div
		  			
	<div class="form-group">
		<label class="col-sm-2 control-label"></label>								
	 	<div class="col-md-10" style="margin-top:10px; padding-top:10px;">								
			<%= f.submit 'Update my account', :class => 'btn btn-success' %> or <%= link_to 'Cancel', admin_account_path %>	
		</div>
	</div>		
<% end %>
</section>

<script type="text/javascript">

$(document).ready(function() { 
    $('.timepicker').timepicker({
                minuteStep: 15,
                showInputs: false,
                disableFocus: true
            });
  	$(".lnk-close").click(function(){
  		$(this).parent().parent().find('.is-closed').val('t');
  		$(this).parent().parent().find('[data-view="is-closed"]').css("display","block");
  		$(this).parent().parent().find('[data-view="is-open"]').css("display","none");
  	});
  	
  	  	$(".lnk-open").click(function(){
  		$(this).parent().parent().find('.is-closed').val('f');
  		$(this).parent().parent().find('[data-view="is-closed"]').css("display","none");
  		$(this).parent().parent().find('[data-view="is-open"]').css("display","block");
  	});
  	
 
	$('body').on('click', '.btn-remove-holiday' , function(e){
		$(this).parent().parent().find('input[type=hidden]').val('1');
		$(this).parent().parent().hide();
		e.preventDefault();		
	})
	
	$('body').on('click', '.add_fields' , function(e){		
		var time = new Date().getTime();		
		var regexp = new RegExp($(this).data('id'), 'g');
		$(this).before($(this).data('fields').replace(regexp, time));
		$('.holiday-date').datepicker(
			{
				format:'dd-M-yyyy',
				todayHighlight: true,
				autoclose:true,
				allowEmpty:false
			});
		e.preventDefault()	
	})
	
	$('.holiday-date').datepicker(
			{
				format:'dd-M-yyyy',
				todayHighlight: true,
				autoclose:true,
				allowEmpty:false
			});
	 	
 });
	
</script>

app/views/admin/account/show.html.erb
<%- title "Calendo | " + @account.name %>

<section style="padding:15px;">
	<header>
		<h3 style="margin-top:10px;">Account: <%= @account.name %> 
		<%= link_to admin_edit_account_path do %>
				<span class="entity-action-link"><i class="fa fa-edit"></i> Edit my account</span> 
			<% end %> 	 
		</h3>
		<hr style="margin-top:5px;"/>
	</header>
	<div class="bs-callout bs-callout-info">
								<h4>Basic settings</h4>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal">Company name:</label>
									</div>
									<div class="col-sm-9" >
										<label class="normal"><%= @account.name %></label>
									</div>
								</div>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal">Public link:</label>
									</div>
									<div class="col-sm-9" >
										<label class="normal"><%= link_to root_url(:subdomain => @account.subdomain)%></label>
									</div>
								</div>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal">Language:</label>
									</div>
									<div class="col-sm-9" >
										<label class="normal">English US</label>
									</div>
								</div>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal">Timezone:</label>
									</div>
									<div class="col-sm-9" >
										<label class="normal"><%= @account.time_zone %></label>
									</div>
								</div>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal">Description:</label>
									</div>
									<div class="col-sm-9" >
										<label class="normal">Ut nisi dolor, dignissim a aliquet quis, vulputate id dui. Proin ultrices ultrices ligula, dictum varius turpis faucibus non. Curabitur faucibus ultrices nunc, nec aliquet leo tempor cursus</label>
									</div>
								</div>
								
								

							</div>
							
							<div class="bs-callout bs-callout-warning">
								<h4>Business hours</h4>
								<% @account.business_hours.order(:id).each do |bh|%>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-3" style="text-align:right;" >		
										<label class="normal"><%= bh.day.humanize %>:</label>
									</div>
									<div class="col-sm-9" >
										<% if bh.is_closed %>
											<label class="normal">CLOSED</label>
										<% else %>
											<label class="normal"><%= bh.open_time + " - " + bh.close_time%></label>
										<% end %>	
									</div>
								</div>
								<% end %>
								
							</div>
							<div class="bs-callout bs-callout-warning">
								<h4>Address</h4>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-1" style="text-align:right;" >		
										<label class="normal"></label>
									</div>
									<div class="col-sm-11" >
										<label class="normal">123 Main St.</label>
									</div>
								</div>
								<div class="row" style="border-bottom: 1px solid #EDEDED; margin-left:-5px; margin-right:5px;">
									<div class="col-sm-1" style="text-align:right;" >		
										<label class="normal"></label>
									</div>
									<div class="col-sm-11" >
										<label class="normal">Vancouver, BC, V1V 1V1, Canada</label>
									</div>
								</div>
								
							</div>
</section>